# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tree-Numbered-DB
version:      1.02.2
version_from: DB.pm
installdirs:  site
requires:
    Tree::Numbered:                1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
